theme: jekyll-theme-minimal
title: Lauren Sorensen
description: media preservation, conservation, archives consulting services
logo: https://raw.githubusercontent.com/laurensorensen/laurensorensen.github.io/master/me.png
