theme: jekyll-theme-minimal
title: Lauren Sorensen
description: media preservation, conservation, archives consulting services
logo: [Location of the logo]
google_analytics: [Your Google Analytics tracking ID]
